version: "3.8"

services:
  frontend:
    build: ./frontend
    ports:
      - 3000:3000

  backend:
    build: ./backend
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=postgres://your_postgres_user:your_postgres_password@postgres:5432/stimme_local
    depends_on:
      - postgres
    volumes:
      - ./backend/media:/app/media
 
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: stimme_local
      POSTGRES_USER: claudron
      POSTGRES_PASSWORD: open
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
